---
language: node_js
node_js:
  - "4"
  - "5"
  - "6"

sudo: false

cache:
  directories:
    - node_modules

matrix:
  fast_finish: true

before_install:
  - "npm i -g npm@5"

install:
  - npm i -g bower
  - npm i

script:
  - npm t
