---
language: node_js
node_js:
  - "0.12"

sudo: false

cache:
  directories:
    - node_modules

matrix:
  fast_finish: true

before_install:
  - "npm config set progress false"
  - "npm install -g npm@^3"

install:
  - npm install -g bower
  - npm install

script:
  - npm test
